Repository TUSB/TheUnusualSkyBlock, pull requests merged in 2025-01, with the labels that each got.

#646 モブのステータス付与処理
  data/entity/function/spawn/apply_status/.mcfunction
  data/entity/function/spawn/apply_status/act.mcfunction
  data/entity/function/spawn/apply_status/mob.mcfunction
  data/entity/function/spawn/apply_status/status/attack.mcfunction
  data/entity/function/spawn/apply_status/status/defense.mcfunction
  data/entity/function/spawn/apply_status/status/hp.mcfunction
  data/entity/function/spawn/apply_status/status/mp.mcfunction
  data/entity/function/spawn/apply_status/status/special_attack.mcfunction
  data/entity/function/spawn/apply_status/status/special_defense.mcfunction
  data/entity/loot_table/name_with_level.json
  data/skill/functions/act/common/condemnation/effect1.mcfunction
  data/skill/functions/act/common/weakness_paint/clear.mcfunction
  data/skill/functions/act/common/weakness_paint/hit.mcfunction
  data/skill/functions/act/summoner/summon_wolf/act1.mcfunction
  data/skill/functions/enemy/change_status/attack.mcfunction
  data/skill/functions/enemy/change_status/defense.mcfunction
  data/skill/functions/enemy/change_status/hp.mcfunction
  data/skill/functions/enemy/change_status/level/.mcfunction
  data/skill/functions/enemy/change_status/level/rename.mcfunction
  data/skill/functions/enemy/change_status/mp.mcfunction
  data/skill/functions/enemy/change_status/special_attack.mcfunction
  data/skill/functions/enemy/change_status/special_defense.mcfunction
Labels: 優先度: 高い

#652 スポーン位置チェックのreturnコマンドが不足していたバグを修正
  data/entity/function/spawn/correction_pos/check_block.mcfunction
Labels: 優先度: 低い

#642 メテオストライクの属性・威力を変更
  data/skill/functions/data/black_mage.mcfunction
Labels: 1-19-4, 優先度: 高い

#643 ホーリーの威力を変更
  data/skill/functions/data/white_mage.mcfunction
Labels: 1-19-4, 優先度: 高い

#655 スキル削除機能の1.19.4移植
  data/makeup/functions/skill/trigger/error/mismatched_trigger.mcfunction
  data/skill/functions/trigger/tellraw/init.mcfunction
Labels: バグ / 機能修正, 1-19-4, 優先度: 高い

#654 5属性耐性を削除
  data/enemy/functions/show_damage/health_minus.mcfunction
  data/enemy/functions/show_damage/health_plus.mcfunction
  data/enemy/functions/show_damage/show.mcfunction
  data/enemy/loot_tables/weak_recover_element.json
  data/entity/function/spawn/apply_status/mob.mcfunction
  data/entity/function/spawn/set_spawner/each_mob.mcfunction
  data/main/function/load_once.mcfunction
  data/makeup/functions/skill/enchant/elemental_damage/hit.mcfunction
  data/player/functions/trigger/hurt_entity/hit_projectile.mcfunction
  data/player/functions/trigger/hurt_entity/melee_attack.mcfunction
  data/skill/functions/act/common/libra/success.mcfunction
  data/skill/functions/act/common/life_scouter/element_text.mcfunction
  data/skill/functions/act/common/life_scouter/success.mcfunction
  data/skill/functions/act/white_mage/sanctuary/apply_enemy.mcfunction
  data/skill/functions/enemy/change_status/.mcfunction
  data/skill/functions/enemy/change_status/element_dark.mcfunction
  data/skill/functions/enemy/change_status/element_fire.mcfunction
  data/skill/functions/enemy/change_status/element_ice.mcfunction
  data/skill/functions/enemy/change_status/element_light.mcfunction
  data/skill/functions/enemy/change_status/element_lightning.mcfunction
  data/skill/loot_tables/life_scouter.json
Labels: 優先度: 通常

#659 黒材/白材強化の修正の1.19.4移植
  data/item/functions/sign/click/upgrade_black.mcfunction
  data/item/functions/sign/click/upgrade_black/.mcfunction
  data/item/functions/sign/click/upgrade_black/y0_1.mcfunction
  data/item/functions/sign/click/upgrade_black/y2_304.mcfunction
  data/item/functions/sign/click/upgrade_black/y305_319.mcfunction
  data/item/functions/sign/click/upgrade_white/.mcfunction
  data/item/functions/sign/click/upgrade_white/y0_1.mcfunction
  data/item/functions/sign/click/upgrade_white/y2_304.mcfunction
  data/item/functions/sign/click/upgrade_white/y305_319.mcfunction
  data/item/loot_tables/item/magma_cube_spawn_egg/sign/upgrade_black.json
  data/item/loot_tables/item/magma_cube_spawn_egg/sign/upgrade_white.json
Labels: バグ / 機能修正, 1-19-4, 優先度: 高い

#660 ReceivedElementDamageフラグタグを削除
  data/enemy/functions/ai/call/trigger/damage/.mcfunction
  data/enemy/functions/ai/call/trigger/damage/element.mcfunction
  data/enemy/functions/update_health.mcfunction
  data/skill/functions/act/knight/raging_slash/tick.mcfunction
  data/skill/functions/enemy/blink/activate/.mcfunction
Labels: 優先度: 通常

#664 セイクリッドピラーの倍率を制限
  data/skill/functions/act/white_mage/sacred_pillar/act1.mcfunction
  data/skill/functions/act/white_mage/sacred_pillar/player_damage.mcfunction
Labels: バグ / 機能修正, 1-19-4, 優先度: 高い

#663 転移の印板修正の1.19.4移植
  data/item/functions/sign/click/teleport.mcfunction
  data/makeup/functions/item/sign/teleport/after.mcfunction
  data/makeup/functions/item/sign/teleport/before.mcfunction
Labels: バグ / 機能修正, 1-19-4, 優先度: 高い

#666 モブの自然ダメージ
  data/enemy/function/damage/natural.mcfunction
  data/enemy/function/damage/update_health.mcfunction
  data/enemy/function/tick.mcfunction
  data/makeup/function/enemy/damage/damage.mcfunction
Labels: 優先度: 高い, プリーズレビュー

#667 スポナーの岩盤化範囲の縮小
  data/enemy/functions/break_spawner/.mcfunction
  data/enemy/functions/break_spawner/damage_score_get.mcfunction
  data/enemy/functions/break_spawner/enemy_count.mcfunction
  data/enemy/functions/break_spawner/failed_mine.mcfunction
  data/enemy/functions/break_spawner/mined.mcfunction
Labels: 1-19-4, 優先度: 高い

#668 ステークスファイアの失敗時ダメージを変更
  data/skill/functions/act/hunter/stakes_fire/act0.mcfunction
  data/skill/functions/act/hunter/stakes_fire/apply.mcfunction
  data/skill/functions/act/hunter/stakes_fire/failed.mcfunction
Labels: 1-19-4, 優先度: 高い

#671 エンティティ死亡処理
  data/enemy/function/damage/update_health.mcfunction
  data/entity/function/death/act.mcfunction
  data/entity/function/death/check.mcfunction
Labels: 優先度: 通常

#672 Hitダメージの同期処理を追加
  data/enemy/function/damage/hit.mcfunction
  data/enemy/function/tick.mcfunction
Labels: 優先度: 高い, プリーズレビュー

#673 Linter用ツールを追加
  .github/CODEOWNERS
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/DISCUSSION_TEMPLATE/idea.yml
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/idea_request.yml
  .github/PULL_REQUEST_TEMPLATE/bugfix_template.md
  .github/PULL_REQUEST_TEMPLATE/feature_template.md
  .github/linters/.jscpd.json
  .github/linters/.lycheerc
  .github/linters/.markdownlint.json
  .github/linters/.mega-linter.yml
  .github/linters/.prettierrc.json
  .github/linters/.yaml-lint.yml
  .github/pull_request_template.md
  .github/workflows/assign-author.yaml
  .github/workflows/chatgpt-review.yml
  .github/workflows/inactive-issue-pr.yml
  .github/workflows/jekyll-gh-pages.yml
  .github/workflows/lint-datapack.yml
  .github/workflows/notice-deploy.yml
  .github/workflows/sync-feature-priority.yml
  .gitignore
  .travis.yml
  .vscode/settings.json
  README.md
  pack.mcmeta
Labels: プリーズレビュー

#674 エンティティのダメージ管理
  data/entity/damage_type/magic.json
  data/entity/damage_type/physical.json
  data/entity/damage_type/unreasonable.json
  data/entity/function/damage/apply/.mcfunction
  data/entity/function/damage/apply/core/.mcfunction
  data/entity/function/damage/apply/core/apply.macro.mcfunction
  data/entity/function/damage/apply/core/mob.mcfunction
  data/entity/function/damage/apply/core/player.mcfunction
  data/entity/function/damage/apply/core/resolve_percentage_damage/.mcfunction
  data/entity/function/damage/apply/core/resolve_percentage_damage/mob.mcfunction
  data/entity/function/damage/apply/core/resolve_percentage_damage/player.mcfunction
  data/entity/function/damage/apply/magic.mcfunction
  data/entity/function/damage/apply/physical.mcfunction
  data/entity/function/damage/apply/unreasonable.mcfunction
  data/entity/predicate/damage/check_death.json
  data/minecraft/tags/damage_type/bypasses_cooldown.json
  data/minecraft/tags/damage_type/no_knockback.json
Labels: 優先度: 高い, プリーズレビュー

#679 Code レビューのタイミング修正
  .github/workflows/chatgpt-review.yml
Labels: プリーズレビュー

#675 火だるまでのpredicateパスを修正
  data/effect/function/burn/tick.mcfunction
Labels: 優先度: 通常

#676 特殊デバフ付与の中断条件を各apply内に移動
  data/effect/function/burn/apply.mcfunction
  data/effect/function/confuse/apply.mcfunction
  data/effect/function/curse/apply.mcfunction
  data/effect/function/doom/apply.mcfunction
  data/effect/function/doom/apply_super.mcfunction
  data/effect/function/freeze/apply0.mcfunction
  data/effect/function/pale/apply.mcfunction
  data/effect/function/palsy/apply.mcfunction
  data/effect/function/tnt/apply.mcfunction
  data/effect/function/too_bad_effect.mcfunction
  data/effect/function/virus/apply.mcfunction
Labels: 優先度: 低い

#680 ダメージのセーブとロードを追加
  data/entity/function/damage/apply/core/.mcfunction
  data/entity/function/damage/load.mcfunction
  data/entity/function/damage/modify.mcfunction
  data/entity/function/damage/save.mcfunction
Labels: 優先度: 高い, プリーズレビュー

#684 忍者スキルのダメージをバフ
  data/skill/functions/data/ninja.mcfunction
Labels: 1-19-4, 優先度: 高い, リリース予定

#694 [feature] 砂利のルートテーブルを一部調整して序盤の資材不足の緩和 #685
  data/item/loot_tables/group/block/gravel.json
Labels: 1-19-4, 優先度: 通常, リリース予定

#695 update/v13-2-5-alpha2 ブランチにGitHub WorkFlowなどの設定を反映
  .github/CODEOWNERS
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/DISCUSSION_TEMPLATE/idea.yml
  .github/FUNDING.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/idea_request.yml
  .github/ISSUE_TEMPLATE/todo.yml
  .github/PULL_REQUEST_TEMPLATE/bugfix_template.md
  .github/PULL_REQUEST_TEMPLATE/feature_template.md
  .github/linters/.jscpd.json
  .github/linters/.lycheerc
  .github/linters/.markdownlint.json
  .github/linters/.mega-linter.yml
  .github/linters/.prettierrc.json
  .github/linters/.yaml-lint.yml
  .github/pull_request_template.md
  .github/workflows/.github/workflows/check.yml
  .github/workflows/assign-author.yaml
  .github/workflows/chatgpt-review.yml
  .github/workflows/deploy.yml
  .github/workflows/inactive-issue-pr.yml
  .github/workflows/jekyll-gh-pages.yml
  .github/workflows/lint-datapack.yml
  .github/workflows/notice-deploy.yml
  .github/workflows/notice.yml
  .github/workflows/sync-feature-priority.yml
  .gitignore
  .travis.yml
  .vscode/settings.json
  README.md
  pack.mcmeta
Labels: 1-19-4
