Repository TUSB/TheUnusualSkyBlock, pull requests merged in 2025-03, with the labels that each got.

#731 Tick関係のタスク処理を追加
  data/main/function/task/delayed.mcfunction
  data/main/function/task/native.mcfunction
  data/main/function/task/temporary.mcfunction
  data/main/function/tick.mcfunction
Labels: 優先度: 高い

#712 スキルに関するダメージのタグ名を小文字に変更
  data/entity/functions/projectile_hit/enemy.mcfunction
  data/entity/functions/projectile_hit/friendly.mcfunction
  data/player/function/trigger/hurt_entity/melee_attack.mcfunction
  data/skill/functions/act/black_mage/dark_swamp/act0.mcfunction
  data/skill/functions/act/black_mage/eclipse_flame/act0.mcfunction
  data/skill/functions/act/black_mage/ice_javelin/act0.mcfunction
  data/skill/functions/act/black_mage/meteor_strike/act1.mcfunction
  data/skill/functions/act/black_mage/rock_n_roll/act0.mcfunction
  data/skill/functions/act/common/condemnation/act0.mcfunction
  data/skill/functions/act/common/sonic_burst/act0.mcfunction
  data/skill/functions/act/common/weakness_paint/act0.mcfunction
  data/skill/functions/act/hunter/bird_strike/act0.mcfunction
  data/skill/functions/act/hunter/blast_spark/tick.mcfunction
  data/skill/functions/act/hunter/chain_arrow/act0.mcfunction
  data/skill/functions/act/hunter/photonic_laser/act0.mcfunction
  data/skill/functions/act/hunter/stakes_fire/act0.mcfunction
  data/skill/functions/act/hunter/stakes_fire/apply.mcfunction
  data/skill/functions/act/hunter/wild_cooking/act1.mcfunction
  data/skill/functions/act/hunter/wild_flare/act0.mcfunction
  data/skill/functions/act/hunter/wild_flare/tick_mob.mcfunction
  data/skill/functions/act/knight/aerial_slash/act1.mcfunction
  data/skill/functions/act/knight/divine_shield/act0.mcfunction
  data/skill/functions/act/knight/falcon_slash/act0.mcfunction
  data/skill/functions/act/knight/odin_slash/slash.mcfunction
  data/skill/functions/act/knight/raging_slash/act1.mcfunction
  data/skill/functions/act/knight/shadow_thrust/act1.mcfunction
  data/skill/functions/act/ninja/choyaku/jump.mcfunction
  data/skill/functions/act/ninja/issen/act0.mcfunction
  data/skill/functions/act/ninja/kaishaku/explode2.mcfunction
  data/skill/functions/act/ninja/sayonara/death.mcfunction
  data/skill/functions/act/ninja/shuriken/act0.mcfunction
  data/skill/functions/act/ninja/tsuremai/attack.mcfunction
  data/skill/functions/act/summoner/call_crystal_attack/attack/common.mcfunction
  data/skill/functions/act/summoner/call_crystal_attack/attack/dark.mcfunction
  data/skill/functions/act/summoner/call_crystal_attack/attack/fire.mcfunction
  data/skill/functions/act/summoner/call_crystal_attack/attack/ice.mcfunction
  data/skill/functions/act/summoner/call_crystal_attack/attack/light.mcfunction
  data/skill/functions/act/summoner/call_crystal_attack/attack/lightning.mcfunction
  data/skill/functions/act/summoner/deal/act0.mcfunction
  data/skill/functions/act/summoner/kana_tarai/act0.mcfunction
  data/skill/functions/act/summoner/petit_black/act0.mcfunction
  data/skill/functions/act/summoner/pompom/act0.mcfunction
  data/skill/functions/act/white_mage/holy/act0.mcfunction
  data/skill/functions/act/white_mage/sacred_pillar/success.mcfunction
  data/skill/functions/act/white_mage/shining_bolt/act0.mcfunction
  data/skill/functions/enemy/damage/.mcfunction
  data/skill/functions/enemy/damage/friendly.mcfunction
  data/skill/functions/enemy/damage/mob.mcfunction
Labels: 優先度: 通常

#750 ファランクスの1.21.1移植
  data/makeup/function/skill/act/knight/phalanx/apply.mcfunction
  data/skill/function/act/knight/phalanx/act0.mcfunction
  data/skill/function/act/knight/phalanx/apply.mcfunction
  data/skill/function/act/knight/phalanx/apply1.mcfunction
Labels: 機能開発, 優先度: 高い, 1-21-1

#755 隼斬りの1.21.1移植
  .github/workflows/assign-release-label.yaml
  data/makeup/function/skill/act/knight/falcon_slash/decorate/finalize.mcfunction
  data/makeup/functions/skill/act/knight/falcon_slash/decorate/finalize.mcfunction
  data/skill/function/act/knight/falcon_slash/act0.mcfunction
  data/skill/function/act/knight/falcon_slash/decorate/finalize.mcfunction
  data/skill/function/act/knight/falcon_slash/decorate/initialize.mcfunction
  data/skill/function/act/knight/falcon_slash/decorate/tick.mcfunction
Labels: 機能開発, 優先度: 通常, レビュープリーズ, 1-21-1

#763 DamageJson系ストレージの名称を変更する
  data/job/function/level_up/acquirement/level.mcfunction
  data/skill/function/trigger/set/damage_json.mcfunction
  data/skill/function/trigger/set/set.mcfunction
  data/skill/function/trigger/tellraw/loop.mcfunction
  data/skill/function/tusb_memory/loop.mcfunction
  data/skill/functions/trigger/set/damage_json.mcfunction
  data/skill/functions/trigger/set/set.mcfunction
  data/skill/functions/trigger/tellraw/loop.mcfunction
Labels: バグ / 機能修正, 優先度: 高い, レビュープリーズ, 1-21-1

#768 職業スキルダメージの再分類
  data/skill/function/data/black_mage.mcfunction
  data/skill/function/data/common.mcfunction
  data/skill/function/data/hunter.mcfunction
  data/skill/function/data/knight.mcfunction
  data/skill/function/data/ninja.mcfunction
  data/skill/function/data/summoner.mcfunction
  data/skill/function/data/thief.mcfunction
  data/skill/function/data/white_mage.mcfunction
  data/skill/function/load/common.mcfunction
  data/skill/function/practice/act/common.mcfunction
  data/skill/function/practice/act/ninja.mcfunction
Labels: 1-21-1

#769 魔法・理外ダメージが表示されない不具合を修正
  data/skill/function/trigger/set/damage_json.mcfunction
Labels: バグ / 機能修正, 1-21-1

#771 アイアンウィルの1.21.1移植
  data/makeup/function/skill/act/knight/iron_will/act0.mcfunction
  data/makeup/function/skill/act/knight/iron_will/end.mcfunction
  data/makeup/function/skill/act/knight/iron_will/load.mcfunction
  data/skill/advancement/iron_will.json
  data/skill/function/act/knight/iron_will/act0.mcfunction
  data/skill/function/act/knight/iron_will/load.mcfunction
  data/skill/function/act/knight/iron_will/save.mcfunction
  data/skill/function/act/knight/iron_will/sneak.mcfunction
  data/skill/function/act/knight/iron_will/tick.mcfunction
  data/skill/function/act/knight/iron_will/trigger.mcfunction
  data/skill/function/player_tick.mcfunction
Labels: 機能開発, 優先度: 通常, 1-21-1
