Repository TUSB/TheUnusualSkyBlock, pull requests merged in 2025-02, with the labels that each got.

#686 パーティクルが存在しないログが出ないように修正
  data/settings/functions/enemy/desert/ground/blow/wriggling_sand/main.mcfunction
  data/settings/functions/enemy/global/ground/shoot/angry_tree/angry_golden_apple_bullets.mcfunction
  data/settings/functions/enemy/global/ground/shoot/banana_garbager/banana_bullet.mcfunction
  data/settings/functions/enemy/global/neutrality/shoot/goblin_merchant_mixcooker/banana_dance_wildly.mcfunction
  data/settings/functions/enemy/skylands/friendly/blow/employee/ender.mcfunction
  data/settings/functions/enemy/underworld/ground/blow/bluish_purple_mushroom/spore_bullet.mcfunction
  data/settings/functions/enemy/underworld/ground/blow/heavenly_messenger/main.mcfunction
Labels: 優先度: 高い, リリース予定

#688 任意のアイテムに任意のデータを付与できるバグを修正
  data/item/functions/custom_can_place_on/loop.mcfunction
Labels: 優先度: 高い, リリース予定

#691 復活系スキルで復活地点を失ったときにオーバーワールドで復活するバグを修正
  data/skill/functions/act/white_mage/araise/raise_check.mcfunction
Labels: 1-19-4, 優先度: 高い, リリース予定

#689 チュートリアル中に死んだときにチュートリアルエリア外に復活する問題を修正
  data/tutorial_alpha/functions/system/respawn.mcfunction
Labels: 1-19-4, 優先度: 高い, リリース予定

#697 [feature] 通常世界の自然湧きのデーモンアイの湧き率の緩和 #696
  data/settings/loot_tables/enemy/natural_spawn.json
Labels: 1-19-4, 機能開発, 優先度: 通常, リリース予定

#690 チュートリアル中に死んだときにチュートリアルエリア外に復活する問題を修正(1-21-1)
  data/tutorial_alpha/functions/system/respawn.mcfunction
Labels: 優先度: 低い

#692 復活系スキルで復活地点を失ったときにオーバーワールドで復活するバグを修正(1-21-1)
  data/skill/functions/act/white_mage/araise/raise_check.mcfunction
Labels: 優先度: 低い

#699 main:tickの実行順番を変更
  data/entity/function/tick.mcfunction
  data/main/function/tick.mcfunction
Labels: 優先度: 高い

#687 墓の中身が消失するバグを修正
  data/player/functions/death_item_drop/casual.mcfunction
  data/player/functions/death_item_drop/tomb.mcfunction
Labels: 優先度: 高い, リリース予定

#701 エンティティ数制限を追加
  data/entity/function/count/.mcfunction
  data/entity/function/count/loop.mcfunction
  data/entity/function/one_second.mcfunction
  data/entity/function/tick.mcfunction
Labels: 優先度: 低い

#704 めり込み死亡のチュートリアルを追加
  data/advancement/advancements/tutorial/secret19.json
  data/entity/functions/suffocation.mcfunction
Labels: リリース予定

#708 エンティティのアイテムドロップ
  data/entity/function/loot/.mcfunction
  data/entity/function/loot/loop.mcfunction
  data/entity/function/loot/loot/.mcfunction
  data/entity/function/loot/loot/loot_table.mcfunction
Labels: 優先度: 低い

#677 モブへの攻撃時処理を追加
  data/entity/function/damage/add/physical/melee.mcfunction
  data/entity/function/damage/add/physical/projectile.mcfunction
  data/player/advancement/trigger/hurt_entity.json
  data/player/function/trigger/hurt_entity/.mcfunction
  data/player/function/trigger/hurt_entity/hit_projectile.mcfunction
  data/player/function/trigger/hurt_entity/melee_attack.mcfunction
  data/player/function/trigger/hurt_entity/melee_bow_attack.mcfunction
  data/player/function/trigger/hurt_entity/sword_attack_sweep.mcfunction
  data/player/function/trigger/projectile/load.mcfunction
  data/player/function/trigger/projectile/save.mcfunction
  data/player/function/trigger/use/bow.mcfunction
  data/player/function/trigger/use/crossbow.mcfunction
  data/player/function/trigger/use/trident.mcfunction
Labels: 優先度: 高い

#713 チュートリアルの加筆修正
  data/tutorial_alpha/functions/custom_can_place_on/act0.mcfunction
  data/tutorial_alpha/functions/grass_and_sheep/act0.mcfunction
  data/tutorial_alpha/functions/island_capture/act0.mcfunction
  data/tutorial_alpha/functions/mp/act0.mcfunction
  data/tutorial_alpha/functions/natural_spawn/act0.mcfunction
  data/tutorial_alpha/functions/natural_spawn/elite/act0.mcfunction
  data/tutorial_alpha/functions/skill/burst/act0.mcfunction
  data/tutorial_alpha/functions/skill/burst/act1.mcfunction
  data/tutorial_alpha/functions/skill/set/act0.mcfunction
  data/tutorial_alpha/functions/skill/shortcut/act0.mcfunction
  data/tutorial_alpha/functions/skill/shortcut/act1.mcfunction
  data/tutorial_alpha/functions/skill/show/act0.mcfunction
  data/tutorial_alpha/functions/skill/use/act0.mcfunction
  data/tutorial_alpha/functions/spawner/act0.mcfunction
  data/tutorial_alpha/functions/too_bad_effect/curse/act0.mcfunction
  data/tutorial_alpha/functions/tusbmemory/act0.mcfunction
  data/tutorial_alpha/functions/tusbmemory/act1.mcfunction
Labels: 1-19-4, 優先度: 高い, リリース予定

#714 サヨナラ発動時にバフエフェクトを付与
  data/player/functions/rise/.mcfunction
  data/skill/functions/act/ninja/sayonara/death.mcfunction
  data/skill/functions/act/ninja/sayonara/rise.mcfunction
Labels: 1-19-4, 優先度: 高い, リリース予定

#715 GH-683 Add サヨナラのレイズ発動時にバフエフェクトを付与(1.21.1)
  data/player/function/rise/.mcfunction
  data/skill/functions/act/ninja/sayonara/death.mcfunction
  data/skill/functions/act/ninja/sayonara/rise.mcfunction
Labels: 優先度: 低い

#720 エキスパート専用行商のエニグマの上方修正
  data/settings/functions/enemy/global/friendly/blow/enigma.mcfunction
Labels: 1-19-4, 優先度: 通常, プリーズレビュー, リリース予定

#718 固定商人《貴重品》バンクの更新
  data/settings/functions/enemy/skylands/friendly/blow/employee/bank.mcfunction
Labels: 1-19-4, 優先度: 通常, プリーズレビュー, リリース予定

#716 GH-702 Modify チュートリアルの文章を加筆修正(1.21.1)
  data/tutorial_alpha/functions/custom_can_place_on/act0.mcfunction
  data/tutorial_alpha/functions/grass_and_sheep/act0.mcfunction
  data/tutorial_alpha/functions/island_capture/act0.mcfunction
  data/tutorial_alpha/functions/mp/act0.mcfunction
  data/tutorial_alpha/functions/natural_spawn/act0.mcfunction
  data/tutorial_alpha/functions/natural_spawn/elite/act0.mcfunction
  data/tutorial_alpha/functions/skill/burst/act0.mcfunction
  data/tutorial_alpha/functions/skill/burst/act1.mcfunction
  data/tutorial_alpha/functions/skill/set/act0.mcfunction
  data/tutorial_alpha/functions/skill/shortcut/act0.mcfunction
  data/tutorial_alpha/functions/skill/shortcut/act1.mcfunction
  data/tutorial_alpha/functions/skill/show/act0.mcfunction
  data/tutorial_alpha/functions/skill/use/act0.mcfunction
  data/tutorial_alpha/functions/spawner/act0.mcfunction
  data/tutorial_alpha/functions/too_bad_effect/curse/act0.mcfunction
  data/tutorial_alpha/functions/tusbmemory/act0.mcfunction
  data/tutorial_alpha/functions/tusbmemory/act1.mcfunction
Labels: 優先度: 低い, プリーズレビュー, 1-21-4

#723 NO-ISSUE Modify v13.2.5α2へバージョンタグを変更
  data/settings/functions/version_update/set.mcfunction
Labels: 1-19-4, 優先度: 高い, プリーズレビュー, リリース予定

#722 《両替、貴重品》バンクの話しかけられた際のセリフに「未開封の虚無のバンドル」についてのアドバイスの追加
  data/settings/functions/enemy/skylands/friendly/blow/employee/bank_lines.mcfunction
Labels: 1-19-4, 優先度: 高い, リリース予定

#725 オールドイブリースの名前難解化の解除
  data/item/loot_tables/item/leather_boots/old_iblis_b.json
  data/item/loot_tables/item/leather_chestplate/old_iblis_c.json
  data/item/loot_tables/item/leather_helmet/old_iblis_h.json
  data/item/loot_tables/item/leather_leggings/old_iblis_l.json
Labels: 1-19-4, 優先度: 通常, プリーズレビュー, リリース予定

#726 スカイウォークの説明を追加
  data/skill/functions/data/common.mcfunction
Labels: 1-19-4, 優先度: 高い, プリーズレビュー, リリース予定

#711 スキルダメージに関する処理を追加
  data/skill/function/damage/apply/.mcfunction
  data/skill/function/damage/apply/save_elements.mcfunction
  data/skill/function/damage/load.mcfunction
  data/skill/function/damage/modify.mcfunction
  data/skill/function/damage/save.mcfunction
Labels: 優先度: 高い
