Repository TUSB/TheUnusualSkyBlock, pull requests merged in 2025-04, with the labels that each got.

#776 ディヴァインシールドの1.21.1移植
  data/makeup/function/skill/act/knight/divine_shield/act.mcfunction
  data/skill/function/act/knight/divine_shield/act0.mcfunction
  data/skill/function/act/knight/divine_shield/get_damage.mcfunction
Labels: 機能開発, 優先度: 通常, 1-21-1

#782 デコイの1.21.1移植
  data/makeup/function/skill/act/knight/decoy/act0.mcfunction
  data/skill/function/act/knight/decoy/act0.mcfunction
  data/skill/function/act/knight/decoy/avoid_falling.mcfunction
Labels: 機能開発, 優先度: 通常, 1-21-1

#778 真空斬りの1.21.1移植
  data/makeup/function/skill/act/knight/aerial_slash/fly.mcfunction
  data/skill/function/act/knight/aerial_slash/act0.mcfunction
  data/skill/function/act/knight/aerial_slash/act1.mcfunction
  data/skill/function/act/knight/aerial_slash/hit.mcfunction
  data/skill/function/act/knight/aerial_slash/re_aim.mcfunction
  data/skill/function/act/knight/aerial_slash/tick.mcfunction
  data/skill/function/native_tick.mcfunction
Labels: 機能開発, 優先度: 通常, 1-21-1

#774 ライブラの1.21.1移植
  data/makeup/function/skill/act/common/libra/act0.mcfunction
  data/makeup/function/skill/act/common/libra/success.mcfunction
  data/skill/function/act/common/libra/act0.mcfunction
  data/skill/function/act/common/libra/success.mcfunction
Labels: 優先度: 通常, 1-21-1

#780 鍛冶の1.21.1移植
  data/makeup/function/skill/act/knight/blacksmith/error.mcfunction
  data/makeup/function/skill/act/knight/blacksmith/failure.mcfunction
  data/makeup/function/skill/act/knight/blacksmith/success.mcfunction
  data/skill/function/act/knight/blacksmith/act0.mcfunction
  data/skill/function/act/knight/blacksmith/failure.mcfunction
  data/skill/function/act/knight/blacksmith/success.mcfunction
  data/skill/item_modifier/blacksmith.json
  data/skill/predicates/blacksmith/.json
  data/skill/predicates/blacksmith/add_0.json
  data/skill/predicates/blacksmith/add_1.json
  data/skill/predicates/blacksmith/add_10.json
  data/skill/predicates/blacksmith/add_4.json
  data/skill/predicates/blacksmith/add_7.json
  data/skill/tags/item/blacksmith/.json
  data/skill/tags/item/blacksmith/add_0.json
  data/skill/tags/item/blacksmith/add_1.json
  data/skill/tags/item/blacksmith/add_10.json
  data/skill/tags/item/blacksmith/add_4.json
  data/skill/tags/item/blacksmith/add_7.json
Labels: 機能開発, 優先度: 通常, 1-21-1

#784 MobAIのTurn処理
  data/ai/function/exit/.mcfunction
  data/ai/function/exit/change_turn/.mcfunction
  data/ai/function/exit/change_turn/loop.mcfunction
  data/ai/function/exit/condition.mcfunction
  data/ai/function/exit/exit.mcfunction
  data/ai/function/exit/loop.mcfunction
  data/ai/function/exit/time.mcfunction
  data/ai/function/skill/.mcfunction
  data/ai/function/skill/call.mcfunction
  data/ai/function/skill/loop_range.mcfunction
  data/ai/function/skill/set_interval.mcfunction
  data/ai/function/skill/skip.mcfunction
  data/ai/function/tick.mcfunction
  data/ai/function/turn/.mcfunction
  data/ai/function/turn/exit_next_preparation.mcfunction
  data/ai/function/turn/preparation.mcfunction
  data/ai/predicate/tick_act.json
  data/debug/function/ai/usage_rate_1.mcfunction
  data/debug/function/ai/usage_rate_2.mcfunction
  data/debug/function/ai/usage_rate_3.mcfunction
  data/entity/function/spawn/apply_status/act.mcfunction
  data/main/function/load_once.mcfunction
  data/main/function/tick.mcfunction
Labels: 優先度: 高い, レビュープリーズ, 1-21-1

#786 Callスキルのトリガーを作成
  data/ai/advanement/call_on_attack.json
  data/ai/advanement/call_on_attack_projectile.json
  data/ai/function/call/trigger/attack/mob.mcfunction
  data/ai/function/call/trigger/attack/projectile.mcfunction
  data/ai/function/call/trigger/attack/projectile_source.mcfunction
  data/ai/function/call/trigger/attack/trigger.mcfunction
  data/ai/function/call/trigger/block.mcfunction
  data/ai/function/call/trigger/damage/.mcfunction
  data/ai/function/call/trigger/death.mcfunction
  data/ai/function/call/trigger/initial.mcfunction
  data/ai/function/call/trigger/passenger/.mcfunction
  data/ai/function/call/trigger/passenger/trigger.mcfunction
  data/ai/function/call/trigger/tick.mcfunction
  data/ai/function/call/trigger/time.mcfunction
  data/ai/function/tick.mcfunction
  data/ai/function/turn/.mcfunction
  data/ai/predicate/not_trigger_call_passenger.json
  data/enemy/function/damage/hit.mcfunction
  data/entity/function/cooldown.mcfunction
  data/entity/function/garbage_collection.mcfunction
  data/entity/function/spawn/apply_status/act.mcfunction
  data/smart_motion/function/core/block.mcfunction
Labels: 優先度: 高い, レビュープリーズ, 1-21-1
